// ============================================================================
// CartoonGrass.shader
// ----------------------------------------------------------------------------
// Instanced cartoon grass with interaction bending.
//
// IMPORTANT: this shader uses a VERTEX-SHADER tuft approach instead of a
// geometry shader, because Unity's Graphics.DrawMeshInstanced does NOT
// support geometry shaders (instancing data cannot flow through the GS
// stage). The tuft geometry (several blade quads) is baked into the mesh
// itself by GrassField; each DrawMeshInstanced instance is one tuft, and
// the vertex shader applies wind sway + interaction bend proportional to
// the blade height.
//
// Pipeline:
//   C# (GrassField) -> GrassInteractionField (CPU truth, tested)
//     -> per-frame GPU bake into _GrassInteractionTex (grayscale RT)
//     -> this shader samples the RT per-vertex, bends away from the source
//
// Tuft mesh convention (generated by GrassField):
//   - root at local (0, 0, 0), grows along +Y up to y = 1 (unit tuft)
//   - blades fan out around Y; instance scale.y encodes final tuft height
//   - per-vertex TEXCOORD0: x = blade facing direction (cos/sin of angle),
//     y = height fraction 0(root)..1(tip)
//   - per-vertex TEXCOORD1: wind phase / per-instance random (x)
//
// Lighting: toon two-band quantised NdotL + root->tip gradient + rim.
//
// Unity 6 (URP 17) baked-lighting support - key changes:
//   * Added full LightMode "Meta" pass (MetaInput/MetaFragment) outputting
//     the root->tip gradient as Albedo for the Progressive Lightmapper
//     (relevant when the tuft mesh is placed on a static MeshRenderer;
//     DrawMeshInstanced grass itself is lit by light probes at runtime).
//   * ForwardLit now samples Lightmap / Light Probes via the URP standard
//     macros DECLARE_LIGHTMAP_OR_SH / OUTPUT_LIGHTMAP_UV / OUTPUT_SH /
//     SAMPLE_GI, with keywords LIGHTMAP_ON / DIRLIGHTMAP_COMBINED /
//     LIGHTMAP_SHADOW_MIXING / SHADOWS_SHADOWMASK.
//   * Baked GI is added as indirect light, scaled by the new
//     _BakedGIIntensity property (0..2, default 1). Grass keeps a smooth
//     two-band look, so GI is NOT cel-quantised here (unlike PBRToon).
//   * The previously declared (but unused) main-light shadow keywords are
//     now wired through the shadowmask-aware GetMainLight() overload, so the
//     grass receives realtime + baked (shadowmask) shadows like URP Lit.
// ============================================================================
Shader "CartoonRendering/Grass/CartoonGrass"
{
    Properties
    {
        [Header(Gradient)]
        _RootColor          ("Root Color", Color)         = (0.22, 0.45, 0.16, 1)
        _TipColor           ("Tip Color", Color)          = (0.42, 0.75, 0.28, 1)
        _ShadowColor        ("Shadow Color", Color)       = (0.10, 0.22, 0.08, 1)

        [Header(Toon Light)]
        _ShadowSmooth       ("Shadow Smoothness", Range(0, 0.5)) = 0.06
        _RimStrength        ("Rim Strength", Range(0, 2)) = 0.35

        [Header(Baked GI)]
        _BakedGIIntensity   ("Baked GI Intensity", Range(0, 2)) = 1.0

        [Header(Blade Shape)]
        _BendAmount         ("Bend Amount", Range(0, 1)) = 0.45

        [Header(Wind)]
        _WindSpeed          ("Wind Speed", Range(0, 3)) = 0.8
        _WindStrength       ("Wind Strength", Range(0, 0.6)) = 0.15
        _WindDir            ("Wind Direction (xz)", Vector) = (1, 0, 0.3, 0)

        [Header(Interaction)]
        _InteractionTex     ("Interaction Texture", 2D)   = "black" {}
        _InteractionOrigin  ("Interaction Origin (world xz)", Vector) = (0, 0, 0, 0)
        _InteractionSize    ("Interaction Size (world xz)", Vector) = (20, 20, 0, 0)
        _InteractionSource  ("Interaction Source (world)", Vector) = (0, 0, 0, 0)
        _InteractionPower   ("Interaction Power", Range(0.2, 4)) = 1.2
    }

    SubShader
    {
        Tags
        {
            "RenderType"      = "Opaque"
            "RenderPipeline"  = "UniversalPipeline"
            "Queue"           = "Geometry"
            "IgnoreProjector" = "True"
        }

        LOD 200

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            Cull Off
            ZWrite On
            ZTest LEqual

            HLSLPROGRAM
            #pragma vertex GrassVert
            #pragma fragment GrassFrag
            #pragma target 3.5

            // Instancing for DrawMeshInstanced (vertex stage fully supports it)
            #pragma multi_compile_instancing
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHTS
            #pragma multi_compile _ _ADDITIONAL_LIGHT_SHADOWS
            #pragma multi_compile _ _CLUSTER_LIGHT_LOOP // Forward+
            #pragma multi_compile _ _SHADOWS_SOFT

            // Unity 6 baked-lighting keywords
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile _ DIRLIGHTMAP_COMBINED
            #pragma multi_compile _ LIGHTMAP_SHADOW_MIXING
            #pragma multi_compile _ SHADOWS_SHADOWMASK

            // Adaptive Probe Volumes (Unity 6)
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/ProbeVolumeVariants.hlsl"

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "../Library/WorldBend.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            // ------------------------------------------------------------------
            // Material constants
            // ------------------------------------------------------------------
            CBUFFER_START(UnityPerMaterial)
                float4 _RootColor;
                float4 _TipColor;
                float4 _ShadowColor;
                float  _ShadowSmooth;
                float  _RimStrength;
                float  _BakedGIIntensity;
                float  _BendAmount;
                float  _WindSpeed;
                float  _WindStrength;
                float4 _WindDir;
                float4 _InteractionOrigin;
                float4 _InteractionSize;
                float4 _InteractionSource;
                float  _InteractionPower;
            CBUFFER_END

            TEXTURE2D(_InteractionTex);  SAMPLER(sampler_InteractionTex);

            // ------------------------------------------------------------------
            // Tuft mesh input. One instance = one tuft.
            // ------------------------------------------------------------------
            struct Attributes
            {
                float4 positionOS : POSITION;   // unit tuft, root at 0, tip +Y
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;  // x = blade dir angle, y = height frac
                float  windPhase  : TEXCOORD1;  // per-vertex deterministic phase
                float2 lightmapUV : TEXCOORD2;  // static lightmap UV (Unity 6 baking)
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float3 positionWS : TEXCOORD0;
                float2 bladeUV    : TEXCOORD1; // x = across blade, y = 0(root)..1(tip)
                float3 normalWS   : TEXCOORD2;
                float  fogFactor  : TEXCOORD3;
                // Declares "float2 lightmapUV" (LIGHTMAP_ON) or "half3 vertexSH"
                DECLARE_LIGHTMAP_OR_SH(lightmapUV, vertexSH, 4);
            #ifdef USE_APV_PROBE_OCCLUSION
                float4 probeOcclusion : TEXCOORD5; // Adaptive Probe Volumes
            #endif
            #ifdef _ADDITIONAL_LIGHTS_VERTEX
                half3 vertexLight : TEXCOORD6; // per-vertex additional lights
            #endif
            };

            // ------------------------------------------------------------------
            // Sample interaction field: world xz -> RT uv -> bend strength.
            // ------------------------------------------------------------------
            float SampleInteractionStrength(float3 positionWS)
            {
                float2 worldXZ = positionWS.xz;
                float2 originXZ = _InteractionOrigin.xz;
                float2 sizeXZ = _InteractionSize.xy;

                float2 uv = (worldXZ - originXZ) / max(sizeXZ, 1e-4);
                uv = saturate(uv);
                return SAMPLE_TEXTURE2D_LOD(_InteractionTex, sampler_InteractionTex, uv, 0).r;
            }

            // ------------------------------------------------------------------
            // Vertex: apply wind + interaction bend proportional to height.
            // ------------------------------------------------------------------
            Varyings GrassVert(Attributes input)
            {
                Varyings output;
                UNITY_SETUP_INSTANCE_ID(input);

                // Instance TRS: position + tuft height in scale.y
                float3 rootWS = TransformObjectToWorld(float3(0, 0, 0));
                float tuftHeight = max(UNITY_MATRIX_M._m11, 0.05);

                // Height fraction along the blade (0 root .. 1 tip)
                float heightFrac = saturate(input.uv.y);

                // Blade facing: uv.x encodes a direction angle around Y.
                float angle = input.uv.x * 6.2831853;
                float2 facing = float2(cos(angle), sin(angle));

                // Local tuft space (unit): position grows along +Y,
                // blades pre-bent toward +Z in the mesh; we keep that shape
                // and add wind / interaction on top.
                float3 localPos = input.positionOS * tuftHeight;

                // Wind sway grows toward the tip
                float2 windDir = normalize(_WindDir.xz + 1e-4);
                float sway = sin(_Time.y * _WindSpeed + input.windPhase) * _WindStrength;
                localPos.xz += windDir * sway * heightFrac * heightFrac * tuftHeight;

                // Interaction bend: away from the source, stronger near the tip
                float interStrength = SampleInteractionStrength(rootWS);
                float2 toSource = _InteractionSource.xz - rootWS.xz;
                float sourceDist = length(toSource);
                // 压弯方向 = 远离交互源（草被脚踩向外倒伏）；
                // 修复：旧版 bendDir 指向交互源，草会朝向玩家倒（方向反了）
                float2 bendDir = sourceDist > 0.0001 ? -toSource / max(sourceDist, 1e-4) : float2(0, 0);
                float2 interOffset = bendDir * interStrength * _InteractionPower * heightFrac * heightFrac * tuftHeight;
                localPos.xz += interOffset;

                float3 posWS = rootWS + localPos;
                posWS = ApplyWorldBend(posWS); // 世界弯曲
                output.positionWS = posWS;
                output.positionCS = TransformWorldToHClip(posWS);
                output.bladeUV = float2(input.uv.x, heightFrac);

                // Keep the mesh normal, tilted slightly outward by facing
                float3 normalWS = TransformObjectToWorldNormal(input.normalOS);
                output.normalWS = normalize(normalWS + float3(facing.x, 0, facing.y) * 0.15);

                output.fogFactor = ComputeFogFactor(output.positionCS.z);

                // Baked lighting: lightmap UVs or per-vertex SH (mutually exclusive)
                OUTPUT_LIGHTMAP_UV(input.lightmapUV, unity_LightmapST, output.lightmapUV);
                OUTPUT_SH4(output.positionWS, output.normalWS, GetWorldSpaceNormalizeViewDir(output.positionWS), output.vertexSH, output.probeOcclusion);

                #ifdef _ADDITIONAL_LIGHTS_VERTEX
                    output.vertexLight = VertexLighting(output.positionWS, output.normalWS);
                #endif
                return output;
            }

            // ------------------------------------------------------------------
            // Fragment: toon two-band light + root->tip gradient + rim.
            // ------------------------------------------------------------------
            half4 GrassFrag(Varyings input) : SV_Target
            {
                float heightFrac = saturate(input.bladeUV.y);

                // Root -> tip colour gradient
                float3 baseColor = lerp(_RootColor.rgb, _TipColor.rgb, heightFrac);

                float3 normalWS = normalize(input.normalWS);

                // ---------------------------------------------------------------
                // Main light. The shadowmask-aware GetMainLight() overload handles
                // LIGHTMAP_SHADOW_MIXING / SHADOWS_SHADOWMASK exactly like URP Lit.
                // ---------------------------------------------------------------
                half4 shadowMask = half4(1, 1, 1, 1);
                #if defined(SHADOWS_SHADOWMASK) && defined(LIGHTMAP_ON)
                    shadowMask = SAMPLE_SHADOWMASK(input.lightmapUV);
                #endif

                Light mainLight;
                #if defined(_MAIN_LIGHT_SHADOWS) || defined(_MAIN_LIGHT_SHADOWS_CASCADE) || (defined(SHADOWS_SHADOWMASK) && defined(LIGHTMAP_ON))
                    float4 shadowCoord = TransformWorldToShadowCoord(input.positionWS);
                    mainLight = GetMainLight(shadowCoord, input.positionWS, shadowMask);
                #else
                    mainLight = GetMainLight();
                #endif

                // Toon lighting: quantised two-band NdotL (shadowAtten now
                // included so baked shadowmask shadows darken the blades).
                float ndotL = dot(normalWS, mainLight.direction);
                float litTerm = ndotL * mainLight.shadowAttenuation;
                float shadow = 1.0 - smoothstep(0.0, _ShadowSmooth, litTerm);
                float3 lit = lerp(_ShadowColor.rgb, baseColor, 1.0 - shadow);

                // Cheap rim (silhouette light from the back)
                float3 viewDirWS = GetWorldSpaceNormalizeViewDir(input.positionWS);
                float ndotV = saturate(dot(normalWS, viewDirWS));
                float rim = pow(1.0 - ndotV, 2.0) * _RimStrength * (1.0 - shadow * 0.5);
                lit += rim * _TipColor.rgb;

                // Main light colour + ambient (simple, no shadow probe)
                lit *= mainLight.color;

                // ---------------------------------------------------------------
                // Baked GI (lightmap / light probes) as INDIRECT light. Grass
                // keeps a soft two-band look, so the GI is NOT cel-quantised
                // here - it just lifts the blades with bounce/environment light.
                // For DrawMeshInstanced grass this resolves to per-vertex SH
                // (light probes), which is the standard way to light instanced
                // grass with baked scenes in Unity 6.
                // ---------------------------------------------------------------
                #if !defined(LIGHTMAP_ON) && (defined(PROBE_VOLUMES_L1) || defined(PROBE_VOLUMES_L2))
                    half4 apvOcclusion = half4(1, 1, 1, 1);
                    half3 bakedGI = SAMPLE_GI(input.vertexSH, GetAbsolutePositionWS(input.positionWS), normalWS,
                                              GetWorldSpaceNormalizeViewDir(input.positionWS), input.positionCS.xy,
                                              input.probeOcclusion, apvOcclusion);
                #else
                    half3 bakedGI = SAMPLE_GI(input.lightmapUV, input.vertexSH, normalWS);
                #endif
                lit += baseColor * bakedGI * _BakedGIIntensity;

                // ---------------------------------------------------------------
                // Additional lights (point / spot). Grass keeps its soft two-band
                // look, so the contribution is NOT cel-quantised.
                // ---------------------------------------------------------------
                #ifdef _ADDITIONAL_LIGHTS_VERTEX
                    lit += baseColor * input.vertexLight;
                #endif
                #if defined(_ADDITIONAL_LIGHTS)
                    // LIGHT_LOOP_BEGIN handles the Forward+ cluster traversal
                    // (plain GetAdditionalLightsCount() returns 0 there). The
                    // macro expects an "inputData" carrying screen UV + posWS.
                    InputData inputData = (InputData)0;
                    inputData.positionWS = input.positionWS;
                    inputData.normalizedScreenSpaceUV = GetNormalizedScreenSpaceUV(input.positionCS);
                    LIGHT_LOOP_BEGIN(GetAdditionalLightsCount())
                        Light addLight = GetAdditionalLight(lightIndex, input.positionWS, shadowMask);
                        float addAtten = addLight.distanceAttenuation * addLight.shadowAttenuation;
                        float addNdotL = saturate(dot(normalWS, addLight.direction));
                        lit += baseColor * addLight.color.rgb * addNdotL * addAtten;
                    LIGHT_LOOP_END
                #endif

                float fog = ComputeFogFactor(input.positionCS.z);
                half4 color = half4(lit, 1.0);
                color.rgb = MixFog(color.rgb, fog);
                return color;
            }
            ENDHLSL
        }

        // -------------------------------------------------------------------
        // GBuffer Pass (deferred). Writes the FULLY toon-shaded colour into
        // the lighting buffer (SV_Target3) with albedo/specular zeroed, so
        // URP's deferred PBR light loop adds nothing and the grass look is
        // preserved. The vertex stage repeats the wind/interaction displacement
        // so the GBuffer matches the forward silhouette.
        // -------------------------------------------------------------------
        Pass
        {
            Name "UniversalGBuffer"
            Tags { "LightMode" = "UniversalGBuffer" }

            Cull Off
            ZWrite On
            ZTest LEqual

            HLSLPROGRAM
            #pragma target 4.5
            // Deferred path is not supported on OpenGL-based APIs.
            #pragma exclude_renderers gles3 glcore

            #pragma vertex GrassGBufferVert
            #pragma fragment GrassGBufferFrag

            #pragma multi_compile_instancing
            #pragma multi_compile _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile _ _ADDITIONAL_LIGHTS
            #pragma multi_compile _ _ADDITIONAL_LIGHT_SHADOWS
            #pragma multi_compile _ _CLUSTER_LIGHT_LOOP // Forward+
            #pragma multi_compile _ LIGHTMAP_ON
            #pragma multi_compile _ DIRLIGHTMAP_COMBINED
            #pragma multi_compile _ LIGHTMAP_SHADOW_MIXING
            #pragma multi_compile _ SHADOWS_SHADOWMASK
            #pragma multi_compile_fragment _ _GBUFFER_NORMALS_OCT
            #include_with_pragmas "Packages/com.unity.render-pipelines.universal/ShaderLibrary/ProbeVolumeVariants.hlsl"

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "../Library/WorldBend.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            #include "../Toon/PBRToon.hlsl" // PackToonGBuffer

            CBUFFER_START(UnityPerMaterial)
                float4 _RootColor;
                float4 _TipColor;
                float4 _ShadowColor;
                float  _ShadowSmooth;
                float  _RimStrength;
                float  _BakedGIIntensity;
                float  _BendAmount;
                float  _WindSpeed;
                float  _WindStrength;
                float4 _WindDir;
                float4 _InteractionOrigin;
                float4 _InteractionSize;
                float4 _InteractionSource;
                float  _InteractionPower;
            CBUFFER_END

            TEXTURE2D(_InteractionTex);  SAMPLER(sampler_InteractionTex);

            struct Attributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;
                float  windPhase  : TEXCOORD1;
                float2 lightmapUV : TEXCOORD2;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float3 positionWS : TEXCOORD0;
                float2 bladeUV    : TEXCOORD1;
                float3 normalWS   : TEXCOORD2;
                DECLARE_LIGHTMAP_OR_SH(lightmapUV, vertexSH, 3);
            #ifdef USE_APV_PROBE_OCCLUSION
                float4 probeOcclusion : TEXCOORD4;
            #endif
            };

            float SampleInteractionStrengthGB(float3 positionWS)
            {
                float2 uv = saturate((positionWS.xz - _InteractionOrigin.xz) / max(_InteractionSize.xy, 1e-4));
                return SAMPLE_TEXTURE2D_LOD(_InteractionTex, sampler_InteractionTex, uv, 0).r;
            }

            // Same displacement as the forward vertex stage.
            Varyings GrassGBufferVert(Attributes input)
            {
                Varyings output;
                UNITY_SETUP_INSTANCE_ID(input);

                float3 rootWS = TransformObjectToWorld(float3(0, 0, 0));
                float tuftHeight = max(UNITY_MATRIX_M._m11, 0.05);
                float heightFrac = saturate(input.uv.y);

                float angle = input.uv.x * 6.2831853;
                float2 facing = float2(cos(angle), sin(angle));

                float3 localPos = input.positionOS * tuftHeight;

                float2 windDir = normalize(_WindDir.xz + 1e-4);
                float sway = sin(_Time.y * _WindSpeed + input.windPhase) * _WindStrength;
                localPos.xz += windDir * sway * heightFrac * heightFrac * tuftHeight;

                float interStrength = SampleInteractionStrengthGB(rootWS);
                float2 toSource = _InteractionSource.xz - rootWS.xz;
                float sourceDist = length(toSource);
                float2 bendDir = sourceDist > 0.0001 ? -toSource / max(sourceDist, 1e-4) : float2(0, 0);
                localPos.xz += bendDir * interStrength * _InteractionPower * heightFrac * heightFrac * tuftHeight;

                float3 posWS = rootWS + localPos;
                posWS = ApplyWorldBend(posWS); // 世界弯曲
                output.positionWS = posWS;
                output.positionCS = TransformWorldToHClip(posWS);
                output.bladeUV = float2(input.uv.x, heightFrac);

                float3 normalWS = TransformObjectToWorldNormal(input.normalOS);
                output.normalWS = normalize(normalWS + float3(facing.x, 0, facing.y) * 0.15);

                OUTPUT_LIGHTMAP_UV(input.lightmapUV, unity_LightmapST, output.lightmapUV);
                OUTPUT_SH4(output.positionWS, output.normalWS, GetWorldSpaceNormalizeViewDir(output.positionWS), output.vertexSH, output.probeOcclusion);
                return output;
            }

            ToonGBufferFragOutput GrassGBufferFrag(Varyings input)
            {
                float heightFrac = saturate(input.bladeUV.y);
                float3 baseColor = lerp(_RootColor.rgb, _TipColor.rgb, heightFrac);
                float3 normalWS = normalize(input.normalWS);

                half4 shadowMask = half4(1, 1, 1, 1);
                #if defined(SHADOWS_SHADOWMASK) && defined(LIGHTMAP_ON)
                    shadowMask = SAMPLE_SHADOWMASK(input.lightmapUV);
                #endif

                Light mainLight;
                #if defined(_MAIN_LIGHT_SHADOWS) || defined(_MAIN_LIGHT_SHADOWS_CASCADE) || (defined(SHADOWS_SHADOWMASK) && defined(LIGHTMAP_ON))
                    float4 shadowCoord = TransformWorldToShadowCoord(input.positionWS);
                    mainLight = GetMainLight(shadowCoord, input.positionWS, shadowMask);
                #else
                    mainLight = GetMainLight();
                #endif

                float ndotL = dot(normalWS, mainLight.direction);
                float litTerm = ndotL * mainLight.shadowAttenuation;
                float shadow = 1.0 - smoothstep(0.0, _ShadowSmooth, litTerm);
                float3 lit = lerp(_ShadowColor.rgb, baseColor, 1.0 - shadow);

                float3 viewDirWS = GetWorldSpaceNormalizeViewDir(input.positionWS);
                float ndotV = saturate(dot(normalWS, viewDirWS));
                float rim = pow(1.0 - ndotV, 2.0) * _RimStrength * (1.0 - shadow * 0.5);
                lit += rim * _TipColor.rgb;

                lit *= mainLight.color;

                #if !defined(LIGHTMAP_ON) && (defined(PROBE_VOLUMES_L1) || defined(PROBE_VOLUMES_L2))
                    half4 apvOcclusion = half4(1, 1, 1, 1);
                    half3 bakedGI = SAMPLE_GI(input.vertexSH, GetAbsolutePositionWS(input.positionWS), normalWS,
                                              viewDirWS, input.positionCS.xy,
                                              input.probeOcclusion, apvOcclusion);
                #else
                    half3 bakedGI = SAMPLE_GI(input.lightmapUV, input.vertexSH, normalWS);
                #endif
                lit += baseColor * bakedGI * _BakedGIIntensity;

                // Additional lights (point / spot) - evaluated here because the
                // deferred light loop adds nothing (albedo = 0).
                #if defined(_ADDITIONAL_LIGHTS)
                    // Forward+ compatible traversal (see forward pass notes).
                    InputData inputData = (InputData)0;
                    inputData.positionWS = input.positionWS;
                    inputData.normalizedScreenSpaceUV = GetNormalizedScreenSpaceUV(input.positionCS);
                    LIGHT_LOOP_BEGIN(GetAdditionalLightsCount())
                        Light addLight = GetAdditionalLight(lightIndex, input.positionWS, shadowMask);
                        float addAtten = addLight.distanceAttenuation * addLight.shadowAttenuation;
                        float addNdotL = saturate(dot(normalWS, addLight.direction));
                        lit += baseColor * addLight.color.rgb * addNdotL * addAtten;
                    LIGHT_LOOP_END
                #endif

                // No MixFog: deferred fog is applied by the pipeline later.
                return PackToonGBuffer(lit, normalWS);
            }
            ENDHLSL
        }

        // -------------------------------------------------------------------
        // DepthNormals Pass - needed for SSAO and deferred decals.
        // The vertex stage repeats the wind/interaction displacement so the
        // normals match the visible silhouette.
        // -------------------------------------------------------------------
        Pass
        {
            Name "DepthNormals"
            Tags { "LightMode" = "DepthNormals" }

            Cull Off
            ZWrite On

            HLSLPROGRAM
            #pragma vertex   GrassDNVert
            #pragma fragment GrassDNFrag
            #pragma multi_compile_instancing
            #pragma multi_compile_fragment _ _GBUFFER_NORMALS_OCT

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "../Library/WorldBend.hlsl"

            CBUFFER_START(UnityPerMaterial)
                float4 _RootColor;
                float4 _TipColor;
                float4 _ShadowColor;
                float  _ShadowSmooth;
                float  _RimStrength;
                float  _BakedGIIntensity;
                float  _BendAmount;
                float  _WindSpeed;
                float  _WindStrength;
                float4 _WindDir;
                float4 _InteractionOrigin;
                float4 _InteractionSize;
                float4 _InteractionSource;
                float  _InteractionPower;
            CBUFFER_END

            TEXTURE2D(_InteractionTex);  SAMPLER(sampler_InteractionTex);

            struct A
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;
                float  windPhase  : TEXCOORD1;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };
            struct V { float4 positionCS:SV_POSITION; float3 normalWS:TEXCOORD0; };

            V GrassDNVert(A input)
            {
                V o;
                UNITY_SETUP_INSTANCE_ID(input);

                float3 rootWS = TransformObjectToWorld(float3(0, 0, 0));
                float tuftHeight = max(UNITY_MATRIX_M._m11, 0.05);
                float heightFrac = saturate(input.uv.y);

                float angle = input.uv.x * 6.2831853;
                float2 facing = float2(cos(angle), sin(angle));

                float3 localPos = input.positionOS * tuftHeight;

                float2 windDir = normalize(_WindDir.xz + 1e-4);
                float sway = sin(_Time.y * _WindSpeed + input.windPhase) * _WindStrength;
                localPos.xz += windDir * sway * heightFrac * heightFrac * tuftHeight;

                float2 uvI = saturate((rootWS.xz - _InteractionOrigin.xz) / max(_InteractionSize.xy, 1e-4));
                float interStrength = SAMPLE_TEXTURE2D_LOD(_InteractionTex, sampler_InteractionTex, uvI, 0).r;
                float2 toSource = _InteractionSource.xz - rootWS.xz;
                float sourceDist = length(toSource);
                float2 bendDir = sourceDist > 0.0001 ? -toSource / max(sourceDist, 1e-4) : float2(0, 0);
                localPos.xz += bendDir * interStrength * _InteractionPower * heightFrac * heightFrac * tuftHeight;

                o.positionCS = TransformWorldToHClip(ApplyWorldBend(rootWS + localPos)); // 世界弯曲
                float3 normalWS = TransformObjectToWorldNormal(input.normalOS);
                o.normalWS = normalize(normalWS + float3(facing.x, 0, facing.y) * 0.15);
                return o;
            }

            half4 GrassDNFrag(V i) : SV_Target
            {
                #if defined(_GBUFFER_NORMALS_OCT)
                    float3 n = normalize(i.normalWS);
                    float2 oct = PackNormalOctQuadEncode(n);
                    float2 remapped = saturate(oct * 0.5 + 0.5);
                    return half4(PackFloat2To888(remapped), 0.0);
                #else
                    return half4(normalize(i.normalWS), 0.0);
                #endif
            }
            ENDHLSL
        }

        // -------------------------------------------------------------------
        // Meta Pass - feeds Albedo to the Progressive Lightmapper.
        // Uses the Unity 6 / URP 17 recommended MetaInput + MetaFragment path.
        // (Grass has no emission; instanced DrawMeshInstanced grass is not
        //  lightmapped anyway - this pass covers static MeshRenderer usage.)
        // -------------------------------------------------------------------
        Pass
        {
            Name "Meta"
            Tags { "LightMode" = "Meta" }

            Cull Off

            HLSLPROGRAM
            #pragma vertex   MetaVert
            #pragma fragment MetaFrag
            #pragma shader_feature EDITOR_VISUALIZATION

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "../Library/WorldBend.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/MetaInput.hlsl"

            CBUFFER_START(UnityPerMaterial)
                float4 _RootColor;
                float4 _TipColor;
                float4 _ShadowColor;
                float  _ShadowSmooth;
                float  _RimStrength;
                float  _BakedGIIntensity;
                float  _BendAmount;
                float  _WindSpeed;
                float  _WindStrength;
                float4 _WindDir;
                float4 _InteractionOrigin;
                float4 _InteractionSize;
                float4 _InteractionSource;
                float  _InteractionPower;
            CBUFFER_END

            struct MetaAttributes
            {
                float4 positionOS : POSITION;
                float2 uv0        : TEXCOORD0;  // x = blade dir, y = height frac
                float2 uv1        : TEXCOORD1;  // static lightmap UV
                float2 uv2        : TEXCOORD2;  // dynamic lightmap UV
            };

            struct MetaVaryings
            {
                float4 positionCS : SV_POSITION;
                float  heightFrac : TEXCOORD0;
            #ifdef EDITOR_VISUALIZATION
                float2 VizUV      : TEXCOORD1;
                float4 LightCoord : TEXCOORD2;
            #endif
            };

            MetaVaryings MetaVert(MetaAttributes input)
            {
                MetaVaryings output = (MetaVaryings)0;
                output.positionCS = UnityMetaVertexPosition(input.positionOS.xyz, input.uv1, input.uv2);
                output.heightFrac = saturate(input.uv0.y);
            #ifdef EDITOR_VISUALIZATION
                UnityEditorVizData(input.positionOS.xyz, input.uv0, input.uv1, input.uv2, output.VizUV, output.LightCoord);
            #endif
                return output;
            }

            half4 MetaFrag(MetaVaryings input) : SV_Target
            {
                // Bake the visible root->tip gradient as albedo.
                UnityMetaInput metaInput;
                metaInput.Albedo   = lerp(_RootColor.rgb, _TipColor.rgb, input.heightFrac);
                metaInput.Emission = half3(0, 0, 0);
            #ifdef EDITOR_VISUALIZATION
                metaInput.VizUV      = input.VizUV;
                metaInput.LightCoord = input.LightCoord;
            #endif
                return UnityMetaFragment(metaInput);
            }
            ENDHLSL
        }
    }
    Fallback "Universal Render Pipeline/Lit"
}
